### ISSUE TITLE
Unstructured sample JSON in Party Endpoint Documentation

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/myanmarapi.github.io#1]
Hi,

In [Party Endpoint Documentation](http://myanmarapi.github.io/endpoints/party.html), the sample JSON shown for **GET list of party** mismatch the actual structure from API, while the sample JSON for **GET party by ID** reflect the actual response.

Thanks.

_Unstructured_
![screen shot 2015-09-08 at 11 31 41 pm](https://cloud.githubusercontent.com/assets/6995089/9741858/d693454a-5682-11e5-80c5-5c265954f45d.png)

_Structured_
![screen shot 2015-09-08 at 11 31 59 pm](https://cloud.githubusercontent.com/assets/6995089/9741866/d90ee7de-5682-11e5-8055-bd09d6f3a88a.png)

**Comment by DragonVirus** [comment]
@phyominthu Thanks for the issue. We forgot to change the docs after party fields are changed. :)

**Comment by phyominthu** [comment]
@DragonVirus Thanks for the fix but I'm still having an itch. There's a bit left in key names. Double quotes. :)

![screen shot 2015-09-08 at 11 54 15 pm](https://cloud.githubusercontent.com/assets/6995089/9742222/ef3b183c-5684-11e5-9665-e79ddc848d28.png)
